version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:3000"]
    volumes:
      - chromadb_data:/chroma/chroma
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml

volumes:
  chromadb_data:
    driver: local